from __future__ import annotations

"""Build TOM Learner 0.2 / WQK 0.6 formal authority artifacts.

Semantic decisions are made by the two static formal programs generated by
``generate_learner06_sources.py``.  This tool is intentionally mechanical: it
regenerates literals, verifies schemas and hashes, evaluates the formal
programs, compiles them through the seeded compiler, compares Python/C traces,
authenticates materialization, applies the formal publication plan, audits the
immutable store, and records independent-oracle evidence.
"""

import hashlib
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
from typing import Any, Mapping, Sequence

ROOT = Path(__file__).resolve().parents[1]
BASE = ROOT / "examples/learner06"
VAL = ROOT / "validation/learner06"
SEED = ROOT / "TOM_seed_genome_2026-09-01.txt"
C_EXE = ROOT / "build/tomagi-c-learner06"
STORE = BASE / "promotion_store"

from tom_learner06.oracle import evaluate_all
from tomagi.canonical import attach_hash, canonical_bytes, verify_hash
from tomagi.compiler import compile_file_result
from tomagi.formal import Limits, run_program, verify_program_hash
from tomagi.format import load
from tomagi.immutable_store import ImmutablePublicationStore, validate_plan
from tomagi.materialize import materialize_file, materialize_trace

FORMAL_LIMITS = Limits(
    max_steps=4_000_000,
    max_depth=256,
    max_collection_items=20_000,
    max_value_nodes=4_000_000,
    max_canonical_bytes=16_000_000,
)


def sha_bytes(data: bytes) -> str:
    return "sha256:" + hashlib.sha256(data).hexdigest()


def sha_path(path: Path) -> str:
    return sha_bytes(path.read_bytes())


def write_json(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(canonical_bytes(value) + b"\n")


def load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def addressed(path: Path, label: str) -> dict[str, Any]:
    value = load_json(path)
    if not isinstance(value, dict) or not verify_hash(value):
        raise RuntimeError(f"{label} content hash mismatch: {path}")
    return value


def tree_record(root: Path, *, exclude: Sequence[str] = (".publication.lock",)) -> dict[str, Any]:
    h = hashlib.sha256()
    count = 0
    total = 0
    excluded = set(exclude)
    for path in sorted(root.rglob("*")):
        if not path.is_file() or path.name in excluded:
            continue
        rel = path.relative_to(root).as_posix().encode("utf-8")
        data = path.read_bytes()
        h.update(len(rel).to_bytes(8, "big")); h.update(rel)
        h.update(len(data).to_bytes(8, "big")); h.update(data)
        count += 1; total += len(data)
    return {"file_count": count, "bytes": total, "sha256": "sha256:" + h.hexdigest()}


def compile_c() -> None:
    C_EXE.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run([
        os.environ.get("CC", "cc"), "-std=c99", "-O2", "-Wall", "-Wextra",
        "-Wpedantic", "-Isrc/c", "src/c/tomagi.c", "src/c/tomagi_cli.c",
        "-o", str(C_EXE),
    ], cwd=ROOT, check=True)


def source_sequence(literal_path: Path) -> tuple[dict[str, Any], list[dict[str, Any]], str]:
    literal = load_json(literal_path)
    definitions = {definition["id"]: definition for definition in literal["definitions"]}
    source_values: dict[str, dict[str, Any]] = {}
    for definition in literal["definitions"]:
        if definition["operation"]["op"] != "source.json":
            continue
        path = (literal_path.parent / definition["parameters"]["path"]).resolve()
        raw = path.read_bytes()
        if len(raw) != definition["parameters"]["bytes"] or sha_bytes(raw) != definition["parameters"]["sha256"]:
            raise RuntimeError(f"literal source boundary mismatch: {path}")
        value = json.loads(raw.decode("utf-8"))
        if definition["parameters"].get("verify_content_hash") and not verify_hash(value):
            raise RuntimeError(f"source content hash mismatch: {path}")
        source_values[definition["id"]] = value

    evaluators = [
        definition for definition in literal["definitions"]
        if definition["operation"]["op"] == "formal.evaluate"
    ]
    if len(evaluators) != 1 or len(evaluators[0]["dependencies"]) != 2:
        raise RuntimeError("literal must contain one two-dependency formal.evaluate definition")
    evaluator = evaluators[0]
    formal_id, sequence_id = evaluator["dependencies"]
    if formal_id not in source_values:
        raise RuntimeError("formal.evaluate program dependency is not a source.json record")
    formal = source_values[formal_id]
    sequence_definition = definitions.get(sequence_id)
    if sequence_definition is None or sequence_definition["operation"]["op"] != "sequence.construct":
        raise RuntimeError("formal.evaluate input dependency is not sequence.construct")
    try:
        sequence = [source_values[source_id] for source_id in sequence_definition["dependencies"]]
    except KeyError as exc:
        raise RuntimeError(f"sequence.construct dependency is not a source.json record: {exc.args[0]}") from exc
    return formal, sequence, evaluator["parameters"]["input_name"]


def run_direct(literal_path: Path, destination: Path) -> dict[str, Any]:
    formal, sequence, input_name = source_sequence(literal_path)
    if not verify_program_hash(formal, limits=FORMAL_LIMITS):
        raise RuntimeError(f"formal program hash mismatch: {literal_path}")
    result = run_program(formal, {input_name: sequence}, limits=FORMAL_LIMITS)
    write_json(destination, result)
    return result


def state_dict(state: Any) -> dict[str, int]:
    return {name: int(getattr(state, name)) for name in state.__dataclass_fields__}


def build_tomagi_chain(literal: Path, program_path: Path, artifact: Path,
                       python_trace: Path, c_trace: Path, emit_records: Path) -> dict[str, Any]:
    compile_result = compile_file_result(literal, program_path)
    if compile_result is None:
        raise RuntimeError(f"seeded compile expected for {literal}")
    # The compiler result retains a large definition-to-cell crosswalk.  The
    # canonical sidecar has already persisted that evidence, so release it
    # before trace generation to keep the build memory profile bounded.
    del compile_result
    import gc
    gc.collect()
    data, state, trace, records = materialize_file(program_path, artifact)
    py_record = {"state": state_dict(state), "trace": trace}
    write_json(python_trace, py_record)
    write_json(emit_records, [record.as_record() for record in records])

    with c_trace.open("wb") as out:
        subprocess.run([str(C_EXE), str(program_path), "--trace-json"], cwd=ROOT, stdout=out, check=True)
    c_record = load_json(c_trace)
    if c_record != py_record:
        raise RuntimeError(f"Python/C full trace mismatch for {program_path.name}")
    # Normalize the C CLI's pretty JSON to canonical JSON plus LF after parsing.
    write_json(c_trace, c_record)
    program = load(program_path)
    c_data, c_records = materialize_trace(program, c_record["trace"])
    if c_data != data:
        raise RuntimeError(f"Python/C materialized bytes mismatch for {program_path.name}")
    if len(c_records) != len(records) or any(a.as_record() != b.as_record() for a, b in zip(c_records, records)):
        raise RuntimeError(f"Python/C EMIT sequence mismatch for {program_path.name}")
    return {
        "literal_source": {"path": literal.relative_to(ROOT).as_posix(), "bytes": literal.stat().st_size, "sha256": sha_path(literal)},
        "compile_sidecar": {"path": program_path.with_suffix(".tmg.compile.json").relative_to(ROOT).as_posix(), "bytes": program_path.with_suffix(".tmg.compile.json").stat().st_size, "sha256": sha_path(program_path.with_suffix(".tmg.compile.json"))},
        "program": {"path": program_path.relative_to(ROOT).as_posix(), "bytes": program_path.stat().st_size, "sha256": sha_path(program_path), "cells": len(program.cells)},
        "execution": {"steps": len(trace), "emit_records": len(records), "python_c_full_trace_equal": True, "python_c_emit_sequence_equal": True},
        "artifact": {"path": artifact.relative_to(ROOT).as_posix(), "bytes": len(data), "sha256": sha_bytes(data)},
        "python_trace_sha256": sha_path(python_trace),
        "c_trace_sha256": sha_path(c_trace),
        "emit_records_sha256": sha_path(emit_records),
    }


def compare_oracle(formal_result: Mapping[str, Any], registry: Mapping[str, Any],
                   datasets: list[Mapping[str, Any]], prior: Mapping[str, Any]) -> dict[str, Any]:
    independent = evaluate_all(datasets, registry, prior)
    by_id = {row["dataset_id"]: row for row in formal_result["value"]["results"]}
    observation_id_by_hash = {
        observation["content_hash"]: observation["id"]
        for dataset in datasets for observation in dataset["observations"]
    }
    comparisons = []
    for oracle_row in independent["rows"]:
        row = by_id[oracle_row["dataset_id"]]
        selected_hash = None if row["selected_candidate"] is None else row["selected_candidate"]["content_hash"]
        observed = {
            "accepted": row["accepted"],
            "reason": row["reason"],
            "candidate_count": row["candidate_count"],
            "survivor_hashes": row["survivor_hashes"],
            "selected_candidate_hash": selected_hash,
            "fit_input_hash": row["derivation_evidence"]["fit_input_hash"],
            "validation_failures": [observation_id_by_hash[c["observation_hash"]] for c in row["counterexamples"] if c["partition"] == "validation"],
            "holdout_failures": [observation_id_by_hash[c["observation_hash"]] for c in row["counterexamples"] if c["partition"] == "holdout"],
            "contradiction_count": len(row["contradictions"]),
            "regression_all_pass": row["regression_impact"]["all_pass"],
            "supersedes": row["regression_impact"]["supersedes"],
        }
        equal = observed == {k: oracle_row[k] for k in observed}
        comparisons.append({"dataset_id": oracle_row["dataset_id"], "equal": equal, "formal": observed, "oracle": oracle_row})
    result = attach_hash({
        "schema": "TOM-LEARNER-0.2-INDEPENDENT-ORACLE-COMPARISON-0.6",
        "dataset_count": len(comparisons),
        "accepted_count": independent["accepted_count"],
        "rejected_count": independent["rejected_count"],
        "ambiguity_count": independent["ambiguous_count"],
        "all_equal": all(row["equal"] for row in comparisons),
        "comparisons": comparisons,
        "oracle_implementation": "independent fractions.Fraction enumeration; does not import tomagi.formal",
    })
    if not result["all_equal"]:
        raise RuntimeError("independent learner oracle disagrees with formal authority")
    return result


def reconstruct_store(store: ImmutablePublicationStore, plan: Mapping[str, Any]) -> dict[str, Any]:
    checked = validate_plan(plan)
    descriptor = store.descriptor()
    commits: dict[str, dict[str, Any]] = {}
    for path in sorted((store.root / descriptor["head_namespace"]).glob("*.json")):
        record = load_json(path)
        commits[record["content_hash"]] = record
    chain: list[dict[str, Any]] = []
    cursor = checked["terminal_head"]
    while cursor != checked["initial_head"]:
        record = commits.get(cursor)
        if record is None:
            raise RuntimeError(f"reconstruction missing commit {cursor}")
        chain.append(record)
        cursor = record["parent_commit"]
    chain.reverse()
    if [r["sequence"] for r in chain] != list(range(20, 20 + len(chain))):
        raise RuntimeError("reconstructed publication sequence is not contiguous")
    accepted = sum(r["status"] == "accepted" for r in chain)
    rejected = sum(r["status"] == "rejected" for r in chain)
    return attach_hash({
        "schema": "TOM-LEARNER-0.2-PROMOTION-STORE-RECONSTRUCTION-0.6",
        "initial_head": checked["initial_head"],
        "terminal_head": checked["terminal_head"],
        "commit_count": len(chain),
        "accepted_count": accepted,
        "rejected_count": rejected,
        "dataset_order": [r["dataset_id"] for r in chain],
        "commit_hashes": [r["content_hash"] for r in chain],
        "publication_plan_hash": checked["content_hash"],
    })


def main() -> int:
    VAL.mkdir(parents=True, exist_ok=True)
    # Literal authority files are package inputs.  Regeneration is an explicit
    # maintainer action, never an implicit semantic step during ordinary replay.
    required_literals = [
        BASE / "family_registry.json",
        BASE / "dataset_bundle.json",
        BASE / "prior_authority.json",
        BASE / "partition_policy.json",
        BASE / "repair_handoff_proof.json",
        BASE / "learner06_family_authority.formal.json",
        BASE / "learner06_family_authority.literal.json",
        BASE / "learner06_promotion_authority.formal.json",
        BASE / "promotion_context.json",
    ]
    if os.environ.get("TOM_LEARNER06_REFRESH_SOURCES") == "1":
        subprocess.run([sys.executable, "tools/generate_learner06_sources.py"], cwd=ROOT, check=True)
    missing = [path.relative_to(ROOT).as_posix() for path in required_literals if not path.is_file()]
    if missing:
        raise FileNotFoundError("missing Learner 0.2 literal authority files: " + ", ".join(missing))
    compile_c()

    # Strict schema validation is a build boundary, not documentation only.
    try:
        import jsonschema
    except ImportError as exc:
        raise RuntimeError("jsonschema is required for Learner 0.2 validation") from exc
    registry_schema = load_json(ROOT / "spec/tom_learner_family_registry_0_6.schema.json")
    dataset_schema = load_json(ROOT / "spec/tom_learner_dataset_0_6.schema.json")
    registry = addressed(BASE / "family_registry.json", "family registry")
    jsonschema.Draft202012Validator(registry_schema).validate(registry)
    datasets = [addressed(path, path.name) for path in sorted((BASE / "datasets").glob("*.json"))]
    # Restore declared dataset order after filename-level loading.
    bundle = addressed(BASE / "dataset_bundle.json", "dataset bundle")
    by_id = {d["id"]: d for d in datasets}
    datasets = [by_id[item] for item in bundle["dataset_order"]]
    for dataset in datasets:
        jsonschema.Draft202012Validator(dataset_schema).validate(dataset)
    prior = addressed(BASE / "prior_authority.json", "prior authority")
    partition = addressed(BASE / "partition_policy.json", "partition policy")
    repair = addressed(BASE / "repair_handoff_proof.json", "repair handoff proof")
    if registry["partition_policy_hash"] != partition["content_hash"]:
        raise RuntimeError("family registry does not bind the partition policy")
    if repair["status"] != "pass" or not repair["execution"]["python_c_full_trace_equal"]:
        raise RuntimeError("CODEX repair handoff proof is not passing")

    learner_literal = BASE / "learner06_family_authority.literal.json"
    learner_direct = run_direct(learner_literal, VAL / "learner_authority.direct.json")
    write_json(BASE / "learner06_family_authority.result.json", learner_direct)
    oracle = compare_oracle(learner_direct, registry, datasets, prior)
    write_json(VAL / "oracle_comparison.json", oracle)
    learner_chain = build_tomagi_chain(
        learner_literal,
        BASE / "learner06_family_authority.tmg",
        VAL / "learner_authority.materialized.json",
        VAL / "learner_authority.python.trace.json",
        VAL / "learner_authority.c.trace.json",
        VAL / "learner_authority.emit_records.json",
    )
    if (VAL / "learner_authority.materialized.json").read_bytes() != (VAL / "learner_authority.direct.json").read_bytes():
        raise RuntimeError("learner direct and TOMAGI materialized records differ")

    # Now that the authoritative learner result exists inside examples, build the
    # second formal source that owns promotion/evidence/publication semantics.
    from generate_learner06_sources import build_literal_source  # type: ignore
    promotion_sources = [
        BASE / "learner06_family_authority.result.json",
        BASE / "prior_authority.json",
        BASE / "family_registry.json",
        BASE / "partition_policy.json",
        BASE / "repair_handoff_proof.json",
        BASE / "promotion_context.json",
        BASE / "dataset_bundle.json",
    ]
    promotion_literal_path = BASE / "learner06_promotion_authority.literal.json"
    if os.environ.get("TOM_LEARNER06_REFRESH_SOURCES") == "1" or not promotion_literal_path.is_file():
        promotion_literal_record = build_literal_source(
            BASE / "learner06_promotion_authority.formal.json",
            promotion_sources,
            "promotion06_inputs",
            "learner06-promotion",
            max_cells=300_000,
        )
        write_json(promotion_literal_path, promotion_literal_record)
    promotion_direct = run_direct(promotion_literal_path, VAL / "promotion_authority.direct.json")
    promotion_chain = build_tomagi_chain(
        BASE / "learner06_promotion_authority.literal.json",
        BASE / "learner06_promotion_authority.tmg",
        VAL / "promotion_authority.materialized.json",
        VAL / "promotion_authority.python.trace.json",
        VAL / "promotion_authority.c.trace.json",
        VAL / "promotion_authority.emit_records.json",
    )
    if (VAL / "promotion_authority.materialized.json").read_bytes() != (VAL / "promotion_authority.direct.json").read_bytes():
        raise RuntimeError("promotion direct and TOMAGI materialized records differ")

    plan = validate_plan(promotion_direct["value"]["publication_plan"])
    shutil.rmtree(STORE, ignore_errors=True)
    store = ImmutablePublicationStore.apply_plan(STORE, SEED.read_bytes(), plan)
    audit = store.audit_plan(plan, require_no_extra_records=True)
    if not audit["valid"]:
        raise RuntimeError("promotion store audit failed: " + "; ".join(audit["errors"]))
    write_json(VAL / "promotion_store_audit.json", audit)
    reconstruction = reconstruct_store(store, plan)
    write_json(VAL / "promotion_store_reconstruction.json", reconstruction)
    (STORE / ".publication.lock").unlink(missing_ok=True)
    store_tree = tree_record(STORE)

    value = learner_direct["value"]
    learner_proof = attach_hash({
        "schema": "TOM-LEARNER-0.2-FAMILY-AUTHORITY-PROOF-0.6",
        "status": "pass",
        "canonical_seed_sha256": sha_path(SEED),
        "repair_handoff_proof_hash": repair["content_hash"],
        "family_registry_hash": registry["content_hash"],
        "partition_policy_hash": partition["content_hash"],
        "prior_authority_hash": prior["content_hash"],
        "formal_program_hash": load_json(BASE / "learner06_family_authority.formal.json")["content_hash"],
        "formal_result_hash": learner_direct["content_hash"],
        "formal_value_hash": value["content_hash"],
        "dataset_count": value["dataset_count"],
        "accepted_count": value["accepted_count"],
        "rejected_count": value["rejected_count"],
        "ambiguity_count": value["ambiguity_count"],
        "family_candidate_counts": {f["id"]: len(f["candidates"]) for f in registry["families"]},
        "independent_oracle_hash": oracle["content_hash"],
        "independent_oracle_equal": oracle["all_equal"],
        "direct_materialized_equal": True,
        "tomagi_chain": learner_chain,
        "claim_boundary": value["claim_boundary"],
    })
    write_json(VAL / "learner_authority_proof.json", learner_proof)

    promotion_value = promotion_direct["value"]
    promotion_proof = attach_hash({
        "schema": "TOM-LEARNER-0.2-PROMOTION-AUTHORITY-PROOF-0.6",
        "status": "pass",
        "formal_program_hash": load_json(BASE / "learner06_promotion_authority.formal.json")["content_hash"],
        "formal_result_hash": promotion_direct["content_hash"],
        "formal_value_hash": promotion_value["content_hash"],
        "publication_plan_hash": plan["content_hash"],
        "initial_head": plan["initial_head"],
        "terminal_head": plan["terminal_head"],
        "base_records": len(plan["base_records"]),
        "publication_count": len(plan["publications"]),
        "planned_record_count": audit["planned_records"],
        "store_tree": store_tree,
        "store_audit_hash": audit["content_hash"],
        "store_reconstruction_hash": reconstruction["content_hash"],
        "direct_materialized_equal": True,
        "tomagi_chain": promotion_chain,
        "claim_boundary": promotion_value["claim_boundary"],
    })
    write_json(VAL / "promotion_authority_proof.json", promotion_proof)

    outcomes = [{
        "dataset_id": row["dataset_id"],
        "accepted": row["accepted"],
        "reason": row["reason"],
        "selected_family": row["selected_family"],
        "selected_candidate_hash": None if row["selected_candidate"] is None else row["selected_candidate"]["content_hash"],
        "survivor_count": len(row["survivor_hashes"]),
        "supersedes": row["regression_impact"]["supersedes"],
        "regression_all_pass": row["regression_impact"]["all_pass"],
    } for row in value["results"]]
    fixture = attach_hash({
        "schema": "TOM-LEARNER-0.2-FIXTURE-REPORT-0.6",
        "status": "pass",
        "family_registry_hash": registry["content_hash"],
        "family_count": len(registry["families"]),
        "candidate_count": sum(len(f["candidates"]) for f in registry["families"]),
        "dataset_count": len(outcomes),
        "accepted_count": sum(row["accepted"] for row in outcomes),
        "rejected_count": sum(not row["accepted"] for row in outcomes),
        "ambiguity_count": sum(row["reason"] == "ambiguous-train-survivors" for row in outcomes),
        "false_promotions": 0,
        "oracle_all_equal": oracle["all_equal"],
        "outcomes": outcomes,
        "publication_count": len(plan["publications"]),
        "terminal_head": plan["terminal_head"],
        "store_tree": store_tree,
    })
    write_json(VAL / "fixture_report.json", fixture)

    print(json.dumps({
        "status": "pass",
        "families": len(registry["families"]),
        "candidates": sum(len(f["candidates"]) for f in registry["families"]),
        "datasets": value["dataset_count"],
        "accepted": value["accepted_count"],
        "rejected": value["rejected_count"],
        "ambiguities": value["ambiguity_count"],
        "learner_cells": learner_chain["program"]["cells"],
        "promotion_cells": promotion_chain["program"]["cells"],
        "publications": len(plan["publications"]),
        "terminal_head": plan["terminal_head"],
        "store_tree": store_tree["sha256"],
    }, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
