from __future__ import annotations

"""Package and independently replay the corrective WQK 0.4.1 release.

This packager treats the superseded 0.4.0 archive as rejected evidence.  The
release root contains only the corrected 0.3 inheritance, the fresh
``tom_world04r`` implementation, literal sources, generated certificates, and
recorded validation.  The final ZIP is deterministic and is replayed from an
extracted copy before publication.
"""

import hashlib
import json
import os
import shutil
import subprocess
import sys
import tempfile
import zipfile
from pathlib import Path, PurePosixPath
from typing import Any, Mapping

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT.parents[1]  # /mnt/data
PACKAGE_NAME = ROOT.name
ZIP_PATH = OUT / f"{PACKAGE_NAME}.zip"
ZIP_ALIAS = OUT / "TOM_WQK_0_4_REBUILT_FIXED.zip"
FIXED_TIME = (2026, 9, 1, 0, 0, 0)
GENERATED = "2026-09-01T00:00:00Z"

CORRECTED_V03_SHA256 = "a7103ec92596fd54198e4a902f078712cf8eafcdf1e45320bbdc02dd53947278"
CORRECTED_INTERVAL_SHA256 = "ea7b3ff2127e8ee7a696eb45e84ae9efdbca7c10c532617c51888fb13cd39f6d"
REJECTED_PRECORRECTION_INTERVAL_SHA256 = "d6bef5b9704a3e5444d86b76e73f6b90a51fdbbf624a6c4705ed0bc7cdef9d4b"
SUPERSEDED_V04_SHA256 = "02d6dad41a602791651bd102a2e4989f41b2807c98e29310e080ddc3c97281b4"
CANONICAL_SEED_SHA256 = "d1417a3136772c0cf3eddcd4962ce07d42cbf87616f7b5bae09fc652d9b807b5"

MANIFEST = ROOT / "checksums/PACKAGE_MANIFEST.json"
CHECKSUMS = ROOT / "checksums/SHA256SUMS.txt"
RELEASE_MANIFEST = OUT / "TOM_World_Query_Kernel_0_4_1_Rebuilt_release_manifest.json"
RELEASE_CHECKSUMS = OUT / "TOM_World_Query_Kernel_0_4_1_Rebuilt_SHA256SUMS.txt"
DELIVERY_SUMMARY = OUT / "TOM_World_Query_Kernel_0_4_1_Rebuilt_DELIVERY_SUMMARY.md"

EXCLUDED_PARTS = {".git", ".pytest_cache", "__pycache__", "build", "dist"}

# Deterministic boundaries regenerated by the fixture, release artifact and
# validation scripts.  Timing-bearing text logs are deliberately excluded from
# byte comparison, while their machine-readable certificates are compared.
REPLAY_FILES = (
    "examples/world04r/piecewise_reference.tmg",
    "validation/world04r/initial_event_set.json",
    "validation/world04r/initial_transition.json",
    "validation/world04r/initial_segment_seal.json",
    "validation/world04r/successor_segment_1.json",
    "validation/world04r/run_indexed.json",
    "validation/world04r/run_exhaustive.json",
    "validation/world04r/run_persisted.json",
    "validation/world04r/trusted_baseline.json",
    "validation/world04r/baseline_comparison.json",
    "validation/world04r/journal_audit.json",
    "validation/world04r/journal_reconstruction.json",
    "validation/world04r/piecewise_reference.python.trace.json",
    "validation/world04r/piecewise_reference.c.trace.json",
    "validation/world04r/tomagi_piecewise_baseline.json",
    "validation/world04r/fixture_report.json",
    "examples/world04r/world04r_release_artifact.tmg",
    "examples/world04r/world04r_release_artifact.tmg.compile.json",
    "validation/world04r/TOM_WORLD_QUERY_KERNEL_0_4_REBUILT_RELEASE.materialized.md",
    "validation/world04r/world04r_release_artifact.python.trace.json",
    "validation/world04r/world04r_release_artifact.c.trace.json",
    "validation/world04r/world04r_release_artifact.emit_records.json",
    "validation/world04r/world04r_release_artifact.proof.json",
)

COMPANIONS = {
    "TOM_0_4_CORRECTIVE_TRUST_RESET.md": "docs/TRUST_RESET_0_4.md",
    "TOM_WORLD_QUERY_KERNEL_0_4_REBUILT.md": "spec/TOM_WORLD_QUERY_KERNEL_0_4_REBUILT.md",
    "TOM_WORLD_QUERY_KERNEL_0_4_REBUILT_RELEASE.md": "TOM_WORLD_QUERY_KERNEL_0_4_REBUILT_RELEASE.md",
    "TOM_AGI_ROADMAP_AND_STARTER_0_4_REBUILT.md": "TOM_AGI_ROADMAP_AND_STARTER_0_4_REBUILT.md",
    "TOM_World_Query_Kernel_0_4_1_corrected_base_pin.json": "sources/CORRECTED_V0_3_BASELINE_PIN.json",
    "TOM_World_Query_Kernel_0_4_1_piecewise_world.json": "examples/world04r/piecewise_world.json",
    "TOM_World_Query_Kernel_0_4_1_piecewise_reference.json": "examples/world04r/piecewise_reference.json",
    "TOM_World_Query_Kernel_0_4_1_piecewise_reference.tmg": "examples/world04r/piecewise_reference.tmg",
    "TOM_World_Query_Kernel_0_4_1_initial_event_set.json": "validation/world04r/initial_event_set.json",
    "TOM_World_Query_Kernel_0_4_1_initial_transition.json": "validation/world04r/initial_transition.json",
    "TOM_World_Query_Kernel_0_4_1_initial_segment_seal.json": "validation/world04r/initial_segment_seal.json",
    "TOM_World_Query_Kernel_0_4_1_successor_segment.json": "validation/world04r/successor_segment_1.json",
    "TOM_World_Query_Kernel_0_4_1_run_indexed.json": "validation/world04r/run_indexed.json",
    "TOM_World_Query_Kernel_0_4_1_run_exhaustive.json": "validation/world04r/run_exhaustive.json",
    "TOM_World_Query_Kernel_0_4_1_baseline_comparison.json": "validation/world04r/baseline_comparison.json",
    "TOM_World_Query_Kernel_0_4_1_journal_audit.json": "validation/world04r/journal_audit.json",
    "TOM_World_Query_Kernel_0_4_1_journal_reconstruction.json": "validation/world04r/journal_reconstruction.json",
    "TOM_World_Query_Kernel_0_4_1_rejection_capsule.json": "validation/world04r/rejection_capsule.json",
    "TOM_World_Query_Kernel_0_4_1_validation_report.json": "validation/world04r/validation_report.json",
    "TOM_World_Query_Kernel_0_4_1_clean_rebuild.json": "validation/world04r/clean_rebuild.json",
    "TOM_World_Query_Kernel_0_4_1_release_artifact_proof.json": "validation/world04r/world04r_release_artifact.proof.json",
    "TOM_seed_genome_2026-09-01.txt": "TOM_seed_genome_2026-09-01.txt",
}


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def write_json(path: Path, value: Mapping[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def clean_transients() -> None:
    for directory in (ROOT / "build", ROOT / "dist", ROOT / ".pytest_cache"):
        shutil.rmtree(directory, ignore_errors=True)
    for directory in sorted(ROOT.rglob("__pycache__"), reverse=True):
        if directory.is_dir():
            shutil.rmtree(directory)
    for pattern in ("*.pyc", "*.pyo", ".DS_Store"):
        for path in ROOT.rglob(pattern):
            if path.is_file():
                path.unlink()
    MANIFEST.unlink(missing_ok=True)
    CHECKSUMS.unlink(missing_ok=True)


def package_files(*, exclude_inventory: bool = False) -> list[Path]:
    excluded = {MANIFEST, CHECKSUMS} if exclude_inventory else set()
    result: list[Path] = []
    for path in ROOT.rglob("*"):
        if not path.is_file() or path in excluded:
            continue
        rel = path.relative_to(ROOT)
        if any(part in EXCLUDED_PARTS for part in rel.parts):
            continue
        if path.suffix in {".pyc", ".pyo"}:
            continue
        result.append(path)
    return sorted(result, key=lambda item: item.relative_to(ROOT).as_posix())


def tree_manifest(path: Path) -> dict[str, Any]:
    entries: list[dict[str, Any]] = []
    for item in sorted(path.rglob("*"), key=lambda p: p.relative_to(path).as_posix()):
        if item.is_file():
            entries.append({
                "path": item.relative_to(path).as_posix(),
                "bytes": item.stat().st_size,
                "sha256": sha256(item),
            })
    canonical = json.dumps(entries, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return {
        "file_count": len(entries),
        "total_bytes": sum(item["bytes"] for item in entries),
        "entries_sha256": sha256_bytes(canonical),
    }


def verify_prerequisites() -> dict[str, Any]:
    required = [ROOT / rel for rel in REPLAY_FILES]
    required.extend(ROOT / rel for rel in COMPANIONS.values())
    required.extend([
        ROOT / "sources/CORRECTED_V0_3_BASELINE_PIN.json",
        ROOT / "src/python/tom_world03/interval.py",
        ROOT / "src/python/tom_world04r/model.py",
        ROOT / "src/python/tom_world04r/journal.py",
        ROOT / "spec/tom_world_piecewise_continuation_0_4_1.schema.json",
    ])
    missing = [path.relative_to(ROOT).as_posix() for path in required if not path.is_file()]
    if missing:
        raise RuntimeError(f"release prerequisite files are missing: {missing}")

    validation = json.loads((ROOT / "validation/world04r/validation_report.json").read_text(encoding="utf-8"))
    if validation.get("status") != "pass" or validation.get("failure_count") != 0:
        raise RuntimeError("corrective validation must pass before packaging")
    if validation.get("corrected_v03_archive_sha256") != CORRECTED_V03_SHA256:
        raise RuntimeError("validation is not bound to the corrected 0.3 archive")
    if validation.get("corrected_interval_sha256") != CORRECTED_INTERVAL_SHA256:
        raise RuntimeError("validation is not bound to the corrected interval implementation")
    if validation.get("prior_v0_4_used_as_source") is not False:
        raise RuntimeError("validation does not exclude the superseded 0.4 line")

    seed = (ROOT / "TOM_seed_genome_2026-09-01.txt").read_bytes()
    if len(seed) != 244 or seed.endswith((b"\n", b"\r")) or sha256_bytes(seed) != CANONICAL_SEED_SHA256:
        raise RuntimeError("canonical TOM seed identity mismatch")
    if sha256(ROOT / "src/python/tom_world03/interval.py") != CORRECTED_INTERVAL_SHA256:
        raise RuntimeError("corrected 0.3 interval implementation mismatch")
    if (ROOT / "src/python/tom_world04").exists():
        raise RuntimeError("superseded tom_world04 namespace is present")

    world = json.loads((ROOT / "examples/world04r/piecewise_world.json").read_text(encoding="utf-8"))
    if any("continuation_until" in relation for relation in world.get("relations", [])):
        raise RuntimeError("relation-authored continuation boundary is present")

    return validation


def write_internal_inventory(validation: Mapping[str, Any]) -> dict[str, Any]:
    listed = package_files(exclude_inventory=True)
    record: dict[str, Any] = {
        "schema": "TOM-WORLD-QUERY-KERNEL-0.4.1-REBUILT-PACKAGE-MANIFEST",
        "package": PACKAGE_NAME,
        "release": "0.4.1-corrective-rebuild",
        "generated": GENERATED,
        "status": "pass",
        "canonical_seed_sha256": CANONICAL_SEED_SHA256,
        "corrected_v03_archive_sha256": CORRECTED_V03_SHA256,
        "corrected_interval_sha256": CORRECTED_INTERVAL_SHA256,
        "rejected_precorrection_interval_sha256": REJECTED_PRECORRECTION_INTERVAL_SHA256,
        "superseded_v04_archive_sha256": SUPERSEDED_V04_SHA256,
        "prior_v0_4_used_as_source": False,
        "validation_content_hash": validation["content_hash"],
        "semantic_chain_sha256": validation["semantic_chain_sha256"],
        "file_count_excluding_manifest_and_checksum": len(listed),
        "files": [
            {
                "path": path.relative_to(ROOT).as_posix(),
                "bytes": path.stat().st_size,
                "sha256": sha256(path),
            }
            for path in listed
        ],
    }
    write_json(MANIFEST, record)
    checksum_files = [path for path in package_files() if path != CHECKSUMS]
    CHECKSUMS.parent.mkdir(parents=True, exist_ok=True)
    CHECKSUMS.write_text(
        "".join(f"{sha256(path)}  {path.relative_to(ROOT).as_posix()}\n" for path in checksum_files),
        encoding="utf-8",
    )
    return record


def make_deterministic_zip() -> list[str]:
    ZIP_PATH.unlink(missing_ok=True)
    ZIP_ALIAS.unlink(missing_ok=True)
    names: list[str] = []
    with zipfile.ZipFile(ZIP_PATH, "w") as archive:
        for path in package_files():
            rel = path.relative_to(ROOT).as_posix()
            name = f"{PACKAGE_NAME}/{rel}"
            info = zipfile.ZipInfo(name, date_time=FIXED_TIME)
            info.create_system = 3
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = (0o100644 & 0xFFFF) << 16
            info.flag_bits |= 0x800
            archive.writestr(
                info,
                path.read_bytes(),
                compress_type=zipfile.ZIP_DEFLATED,
                compresslevel=9,
            )
            names.append(name)
    return names


def validate_zip_name(name: str) -> None:
    value = PurePosixPath(name)
    if value.is_absolute() or not value.parts or value.parts[0] != PACKAGE_NAME:
        raise RuntimeError(f"unsafe archive path {name!r}")
    if any(part in {"", ".", ".."} for part in value.parts):
        raise RuntimeError(f"unsafe archive path {name!r}")


def verify_zip(expected_names: list[str]) -> None:
    with zipfile.ZipFile(ZIP_PATH, "r") as archive:
        infos = archive.infolist()
        names = [info.filename for info in infos]
        if names != expected_names or names != sorted(names) or len(names) != len(set(names)):
            raise RuntimeError("archive member ordering/identity mismatch")
        for info in infos:
            validate_zip_name(info.filename)
            if info.date_time != FIXED_TIME:
                raise RuntimeError(f"archive timestamp is not fixed: {info.filename}")
            if ((info.external_attr >> 16) & 0xFFFF) != 0o100644:
                raise RuntimeError(f"archive mode is not fixed: {info.filename}")
        bad = archive.testzip()
        if bad is not None:
            raise RuntimeError(f"archive CRC failure at {bad}")


def verify_internal_inventory(root: Path) -> None:
    manifest = json.loads((root / "checksums/PACKAGE_MANIFEST.json").read_text(encoding="utf-8"))
    for item in manifest.get("files", []):
        path = root / item["path"]
        if not path.is_file() or path.stat().st_size != item["bytes"] or sha256(path) != item["sha256"]:
            raise RuntimeError(f"internal package manifest mismatch: {item['path']}")

    checksum_path = root / "checksums/SHA256SUMS.txt"
    seen: set[str] = set()
    for line in checksum_path.read_text(encoding="utf-8").splitlines():
        digest, rel = line.split("  ", 1)
        path = root / rel
        if not path.is_file() or sha256(path) != digest:
            raise RuntimeError(f"internal checksum mismatch: {rel}")
        seen.add(rel)
    expected = {
        path.relative_to(root).as_posix()
        for path in root.rglob("*")
        if path.is_file()
        and path != checksum_path
        and not any(part in EXCLUDED_PARTS for part in path.relative_to(root).parts)
    }
    if seen != expected:
        raise RuntimeError(
            f"internal checksum inventory mismatch; missing={sorted(expected-seen)}, extra={sorted(seen-expected)}"
        )


def run_command(cmd: list[str], cwd: Path, timeout: int = 600) -> subprocess.CompletedProcess[str]:
    env = os.environ.copy()
    env["PYTHONPATH"] = str(cwd / "src/python")
    result = subprocess.run(cmd, cwd=cwd, env=env, text=True, capture_output=True, timeout=timeout)
    if result.returncode:
        raise RuntimeError(
            f"archive replay command failed ({result.returncode}): {' '.join(cmd)}\n"
            f"STDOUT:\n{result.stdout}\nSTDERR:\n{result.stderr}"
        )
    return result


def remove_replay_outputs(root: Path) -> None:
    shutil.rmtree(root / "build", ignore_errors=True)
    shutil.rmtree(root / "examples/world04r/continuation_store", ignore_errors=True)
    for rel in REPLAY_FILES:
        (root / rel).unlink(missing_ok=True)
    # Timing-bearing logs are also regenerated but are not hash boundaries.
    for rel in ("validation/world04r/tests.txt", "validation/world04r/clean_rebuild.log"):
        (root / rel).unlink(missing_ok=True)
    (root / "validation/world04r").mkdir(parents=True, exist_ok=True)


def clean_archive_replay() -> dict[str, Any]:
    expected_files = {rel: sha256(ROOT / rel) for rel in REPLAY_FILES}
    expected_store = tree_manifest(ROOT / "examples/world04r/continuation_store")
    with tempfile.TemporaryDirectory(prefix="tom-world04r-final-archive-") as td:
        base = Path(td)
        with zipfile.ZipFile(ZIP_PATH, "r") as archive:
            for info in archive.infolist():
                validate_zip_name(info.filename)
            archive.extractall(base)
        extracted = base / PACKAGE_NAME
        verify_internal_inventory(extracted)
        remove_replay_outputs(extracted)
        (extracted / "build").mkdir(parents=True, exist_ok=True)

        build = run_command([
            "cc", "-std=c99", "-O2", "-Wall", "-Wextra", "-Wpedantic",
            "-Isrc/c", "src/c/tomagi.c", "src/c/tomagi_cli.c", "-o", "build/tomagi-c",
        ], extracted)
        fixture = run_command([sys.executable, "tools/build_world04r_fixture.py"], extracted)
        artifact = run_command([sys.executable, "tools/build_world04r_release_artifact.py"], extracted)
        tests = run_command([
            sys.executable, "-m", "unittest", "discover", "-s", "tests", "-v"
        ], extracted)

        comparisons: dict[str, Any] = {}
        all_equal = True
        for rel, expected in expected_files.items():
            path = extracted / rel
            actual = sha256(path) if path.is_file() else None
            equal = actual == expected
            all_equal &= equal
            comparisons[rel] = {
                "packaged_sha256": expected,
                "replayed_sha256": actual,
                "equal": equal,
            }
        actual_store = tree_manifest(extracted / "examples/world04r/continuation_store")
        store_equal = actual_store == expected_store
        all_equal &= store_equal
        comparisons["examples/world04r/continuation_store/**"] = {
            "packaged": expected_store,
            "replayed": actual_store,
            "equal": store_equal,
        }
        if not all_equal:
            failed = [name for name, item in comparisons.items() if not item["equal"]]
            raise RuntimeError(f"clean final-archive replay mismatch: {failed}")

        import re
        tests_text = tests.stdout + tests.stderr
        match = re.search(r"Ran (\d+) tests", tests_text)
        test_count = int(match.group(1)) if match else 0
        if tests.returncode != 0 or test_count < 144 or not tests_text.rstrip().endswith("OK"):
            raise RuntimeError("full test suite from final archive did not pass")
        packaged_validation = json.loads((extracted / "validation/world04r/validation_report.json").read_text())
        if packaged_validation.get("status") != "pass" or packaged_validation.get("failure_count") != 0:
            raise RuntimeError("packaged corrective validation report is not passing")
        return {
            "zip_crc_and_safe_paths": True,
            "internal_manifest_and_checksums": True,
            "c_build": "pass",
            "fixture_rebuild": "pass",
            "release_artifact_rebuild": "pass",
            "full_test_suite": "pass",
            "full_tests": test_count,
            "packaged_validation_checks": packaged_validation["check_count"],
            "packaged_validation_failures": packaged_validation["failure_count"],
            "compared_file_boundaries": len(expected_files),
            "compared_tree_boundaries": 1,
            "all_replayed_boundaries_equal": True,
            "boundaries": comparisons,
            "command_output_hashes": {
                "c_build": sha256_bytes((build.stdout + build.stderr).encode("utf-8")),
                "fixture": sha256_bytes((fixture.stdout + fixture.stderr).encode("utf-8")),
                "release_artifact": sha256_bytes((artifact.stdout + artifact.stderr).encode("utf-8")),
                "tests": sha256_bytes(tests_text.encode("utf-8")),
            },
        }


def publish_companions() -> list[dict[str, Any]]:
    for name in COMPANIONS:
        (OUT / name).unlink(missing_ok=True)
    published: list[dict[str, Any]] = []
    for name, rel in sorted(COMPANIONS.items()):
        source = ROOT / rel
        destination = OUT / name
        destination.write_bytes(source.read_bytes())
        published.append({
            "path": destination.name,
            "source_in_package": rel,
            "bytes": destination.stat().st_size,
            "sha256": sha256(destination),
        })
    return published


def write_delivery_summary(validation: Mapping[str, Any], replay: Mapping[str, Any]) -> None:
    text = f"""# TOM World & Query Kernel 0.4.1 — Corrective Rebuild Delivery\n\nStatus: **pass**\n\nThis archive supersedes the untrusted 0.4.0 line. It was rebuilt only from the corrected 0.3 archive and does not use prior 0.4 source or evidence.\n\n## Download identity\n\n```text\nPrimary ZIP   {ZIP_PATH.name}\nShort alias   {ZIP_ALIAS.name}\nBytes         {ZIP_PATH.stat().st_size}\nEntries       {len(zipfile.ZipFile(ZIP_PATH).infolist())}\nSHA-256       {sha256(ZIP_PATH)}\nCRC           pass\nSafe paths    pass\n```\n\n## Trust reset\n\n```text\nCorrected 0.3 base       {CORRECTED_V03_SHA256}\nCorrected interval.py    {CORRECTED_INTERVAL_SHA256}\nRejected old interval.py {REJECTED_PRECORRECTION_INTERVAL_SHA256}\nSuperseded 0.4.0 ZIP     {SUPERSEDED_V04_SHA256}\nPrior 0.4 used as source false\n```\n\nThe relation-authored `continuation_until` mechanism is absent and rejected. Every realized segment boundary is an exact corrected-0.3 solver output. Each successor starts at that certified root and remains open to the world horizon.\n\n## Validation\n\n```text\nTests                       {validation['test_count']} passed\nValidation checks           {validation['check_count']} passed\nValidation failures         {validation['failure_count']}\nClean source-capsule replay 24 boundaries equal\nFinal ZIP replay            {replay['compared_file_boundaries'] + replay['compared_tree_boundaries']} boundaries equal\nSemantic chain              {validation['semantic_chain_sha256']}\nValidation content hash     {validation['content_hash']}\n```\n\nCanonical event times are `2, 5, 7, 9`; final exact state is `clock=10, counter=34, mode=5, output=90, x=3`. The TOMAGI ABI remains 128-byte header / 64-byte State64 / 48-byte Cell48 / sixteen opcodes.\n\n## Reproduction\n\n```bash\nmake validate-world04r\nmake package-world04r\n```\n\nThe executed backend evidence covers Python and C99. GPU files remain inherited ABI mappings; this release does not claim a new physical GPU dispatch. The release does not claim arbitrary nonlinear dynamics, autonomous learning, or AGI.\n"""
    DELIVERY_SUMMARY.write_text(text, encoding="utf-8")


def publish_release(
    validation: Mapping[str, Any],
    package_manifest: Mapping[str, Any],
    names: list[str],
    replay: Mapping[str, Any],
) -> dict[str, Any]:
    ZIP_ALIAS.write_bytes(ZIP_PATH.read_bytes())
    if sha256(ZIP_ALIAS) != sha256(ZIP_PATH):
        raise RuntimeError("short ZIP alias is not byte-identical")

    companions = publish_companions()
    write_delivery_summary(validation, replay)
    summary_record = {
        "path": DELIVERY_SUMMARY.name,
        "source_in_package": None,
        "bytes": DELIVERY_SUMMARY.stat().st_size,
        "sha256": sha256(DELIVERY_SUMMARY),
    }

    release: dict[str, Any] = {
        "schema": "TOM-WORLD-QUERY-KERNEL-0.4.1-REBUILT-RELEASE-MANIFEST",
        "release": "0.4.1-corrective-rebuild",
        "generated": GENERATED,
        "status": "pass",
        "source_lineage": {
            "corrected_v03_archive_sha256": CORRECTED_V03_SHA256,
            "corrected_interval_sha256": CORRECTED_INTERVAL_SHA256,
            "rejected_precorrection_interval_sha256": REJECTED_PRECORRECTION_INTERVAL_SHA256,
            "superseded_v04_archive_sha256": SUPERSEDED_V04_SHA256,
            "prior_v0_4_used_as_source": False,
        },
        "package": {
            "path": ZIP_PATH.name,
            "alias": ZIP_ALIAS.name,
            "bytes": ZIP_PATH.stat().st_size,
            "entries": len(names),
            "sha256": sha256(ZIP_PATH),
            "alias_sha256": sha256(ZIP_ALIAS),
            "fixed_zip_timestamp": "2026-09-01T00:00:00",
            "fixed_file_mode": "0100644",
        },
        "internal_inventory": {
            "manifest": "checksums/PACKAGE_MANIFEST.json",
            "checksum_file": "checksums/SHA256SUMS.txt",
            "files_excluding_manifest_and_checksum": package_manifest["file_count_excluding_manifest_and_checksum"],
        },
        "validation": {
            "status": validation["status"],
            "tests": validation["test_count"],
            "checks": validation["check_count"],
            "failures": validation["failure_count"],
            "content_hash": validation["content_hash"],
            "semantic_chain_sha256": validation["semantic_chain_sha256"],
        },
        "archive_replay": replay,
        "accompanying_files": [*companions, summary_record],
        "evidence_boundary": validation["evidence_boundary"],
    }
    write_json(RELEASE_MANIFEST, release)

    targets = [ZIP_PATH, ZIP_ALIAS, RELEASE_MANIFEST, DELIVERY_SUMMARY]
    targets.extend(OUT / name for name in COMPANIONS)
    unique = sorted(set(targets), key=lambda path: path.name)
    RELEASE_CHECKSUMS.write_text(
        "".join(f"{sha256(path)}  {path.name}\n" for path in unique),
        encoding="utf-8",
    )
    return release


def main() -> int:
    validation = verify_prerequisites()
    clean_transients()
    package_manifest = write_internal_inventory(validation)
    names = make_deterministic_zip()
    verify_zip(names)
    replay = clean_archive_replay()
    release = publish_release(validation, package_manifest, names, replay)
    print(json.dumps({
        "status": "pass",
        "package": release["package"],
        "corrected_v03_archive_sha256": CORRECTED_V03_SHA256,
        "prior_v0_4_used_as_source": False,
        "tests": validation["test_count"],
        "validation_checks": validation["check_count"],
        "validation_failures": validation["failure_count"],
        "internal_files_excluding_manifest_and_checksum": package_manifest["file_count_excluding_manifest_and_checksum"],
        "archive_replay_boundaries": replay["compared_file_boundaries"] + replay["compared_tree_boundaries"],
        "release_manifest": RELEASE_MANIFEST.name,
        "release_checksums": RELEASE_CHECKSUMS.name,
        "delivery_summary": DELIVERY_SUMMARY.name,
        "accompanying_files": len(release["accompanying_files"]),
    }, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
